---
defaults:
  - override hydra/sweeper: optuna
hydra:  
  # consider_prior: true
  # prior_weight: 1.0  
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    study_name: crisis2023
    storage: null
    n_trials: 2000
    n_jobs: 1
    params: 
      training.weight_decay: range(0, 0.005, step=0.0001) #0.01 #0.9 #???
      training.learn_rate: choice(0.001, 0.0001, 0.0005)
      model.dropout: range(0, 0.3, step=0.05)
      model.embedding_dim: choice(50, 100, 200)
dataset:
  name: crisis2023_gta #ICEWS14
training:
  epochs: 200 #300 #1000
  evaluate_every: 5
  loss_type: cross_entropy
  algorithm: adam
  weight_decay:  0.0002 # 0.0027  #0.2
  learn_rate:  0.0001 # 0.001
background:
  device: 6
  train_flag: True
  load_flag:  False  #
  result_file_name: results_log
  load_model_name: crisis2023 
model:
  dump_results_flag: True #False
  embedding_dim: 200 # 1024
  dropout: 0.3 #0.3
  decoder: distmult
evaluation:
  early_stopping: 10 # if we do not improve for this amount of epochs: stop!
